### PR TITLE
update repo

### PR DESCRIPTION
**Pull request by moganda12**

### CODE REVIEW

**Comment by moganda12** [comment]
@qwertyuiop265000
please resolve the conflicts, I tried, I failed.

**Comment by qwertyuiop265000** [comment]
I don't know how to do that.
Well, each of the .hjson files mentioned in the list of conflicts has some qwerty-brand proper English implemented instead of no caps, no punctuation English.
And I replaced the .png entirely. 

So you might have to fix it on your end, bud.

**Comment by moganda12** [comment]
sorry I really can't

**Comment by moganda12** [comment]
I would have to use the GitHub CLI, I would never go THAT far.

**Comment by moganda12** [comment]
try merging in my changes and then making a new PR

**Comment by moganda12** [comment]
@qwertyuiop265000
try merging in my changes and then making a new PR

**Pull request closed without merging**
